### ISSUE TITLE
Убрать отправку пустых дат

### ISSUE THREAD

**Issue by bozaro** [bozaro/tech-db-forum#22]
В данный момент на сервер отправляются странные даты, которые могут по-разному обрабатываться на сервере:

 - 1970-01-01T00:00:00.000Z
 - 0001-01-01T00:00:00.000Z

**Comment by slonopotamus** [comment]
Истеричка! 4 коммита.

**Comment by bozaro** [comment]
3 из них не достижимо из мастера ;)
